# Site settings
title: Tarka Indian Kitchen
email: hello@xinyudesign.com
description: > # this means to ignore newlines until "baseurl:"
  Tarka Indian Kitchen Redesign 
baseurl: "/tik" # the subpath of your site, e.g. /blog/
url: "http://xinyudesign.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
# markdown: kramdown
